### ISSUE TITLE
Rename Addresses #1345 - Need Wrap on Name Fields

### ISSUE THREAD

**Issue by SJQuality** [tallyhowallet/extension#1381] opened 2022-04-29 18:38 UTC
### **Build Info:**

[Main Build #2938](https://github.com/tallycash/extension/actions/runs/2245978651)

### **PR/Feature:**
https://github.com/tallycash/extension/pull/1345

### **Reproduction Steps:**

1. Change Account
2. Edit Name
3. Add long name

### **Expected Result:**
Name should wrap and there should be a Maximum amount of characters allowed.

### **Actual Result:**
Chaos :D

See video
https://www.awesomescreenshot.com/video/8671035?key=7fa1ffcad9e2da372009e8c17204371c

**Comment by Shadowfiend** [comment] 2022-04-29 19:54
This is mostly a duplicate of #1354, since we resolve at least some names using external services where we don't control length limitations. 

My 2c is we should not impose a max length in user-set names since we need to solve the UI problem anyway, but will let @mr-michael @VladUXUI do the ultimate assessment there.

**Comment by SJQuality** [comment] 2022-05-02 20:31
@Shadowfiend Yeah, that makes sense. We need to be able to handle it because we can't control what we are given.

**Comment by 0xDaedalus** [comment] 2023-02-10 21:11
Closed in favor of https://github.com/tallyhowallet/extension/issues/1354

**Closed by 0xDaedalus** 2023-02-10 21:11 UTC
Labels: Type: Bug
