### ISSUE TITLE
Logs export returns empty file

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#3019] opened 2023-02-13 07:37 UTC
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Export logs

### What did not work?

Logs file just contain "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"

[logs_v0_22_1__2023-02-13T08_34_59+01_00.txt](https://github.com/tallyhowallet/extension/files/10719728/logs_v0_22_1__2023-02-13T08_34_59%2B01_00.txt)

### Version

v0.22.1

**Comment by jagodarybacka** [comment] 2023-02-13 08:08
Duplicate of https://github.com/tallyhowallet/extension/issues/2938 😉

**Closed by jagodarybacka** 2023-02-13 08:08 UTC
Labels: Type: Bug, Type: Duplicate
