### ISSUE TITLE
Multiple dapp connection windows on Uniswap

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#2915] opened 2023-01-24 16:00 UTC
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

https://user-images.githubusercontent.com/20949277/214343273-48a06faf-9ef4-472c-8df1-d0efd273fa94.mov

### What did not work?

When user is trying to connect to Uniswap with TH as default wallet then and then user clicks the prompt to switch to use other wallet - Uniswap reloads and there are two dapp connection windows.

### Version

None

**Comment by am1993421** [comment] 2023-01-25 10:37
This issue is an old friend, not only on uniswap

**Comment by jagodarybacka** [comment] 2023-01-25 12:00
@am1993421 does it happen only when you click "switch wallet"? Can you give us links to dapps that have this problem?

**Comment by am1993421** [comment] 2023-01-26 03:16
[logs_v0_18_6__2022-12-24T18_37_2808_00.txt](https://github.com/tallyhowallet/extension/files/10506071/logs_v0_18_6__2022-12-24T18_37_2808_00.txt)
I saved a copy of the log from that time
This issue is often raised in the community, and I think it should be taken seriously because it is very much like a virus pop-up, and I remember that Nax has also posted an issue before

**Comment by jagodarybacka** [comment] 2023-01-26 09:24
@am1993421 I assure you it's nothing serious, just a dapp asking to connect wallet at the same time as the wallet wants to connect to dapp. But I see how it may looks suspicious without having that background so I'll change the priority.

**Comment by am1993421** [comment] 2023-01-26 10:05
Yes, I know it's not a terrible issue, but we have to consider the feelings of most users, and hackers scare them @jagodarybacka

**Comment by 0xDaedalus** [comment] 2023-01-27 15:29
Thanks for the logs and feedback here @am1993421  - adding to our next sprint ✅

**Comment by hyphenized** [comment] 2023-02-20 14:24
Could not reproduce, likely to have been fixed by #2983. After clicking on switch wallet, Uniswap reloads and logs `Could not connect eagerly Error: No accounts returned`

**Closed by hyphenized** 2023-02-20 14:24 UTC
Labels: Type: Bug, Priority: Medium, Status: Available
