### ISSUE TITLE
Swaps not working, fee data 'unknown'

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#1865] opened 2022-08-01 06:44 UTC
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1003548904647831582

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

The user is trying to swap & send.

### What did not work?

Transactions are not broadcasted. Remain pending in the extension. The estimated network fee is listed as 'unknown'. 

Logs below:

[logs_v0_14_1__2022-08-01T12_07_4305_30.txt](https://github.com/tallycash/extension/files/9231573/logs_v0_14_1__2022-08-01T12_07_4305_30.txt)

https://etherscan.io/tx/0xf9843dee947ddc978b9fd85c71ff698665fad621bc1adc143c200061e6d296a0  brother

![image](https://user-images.githubusercontent.com/71384922/182088129-5c106f5e-c411-4186-9935-6a1e25069400.png)

![image](https://user-images.githubusercontent.com/71384922/182088159-059f5bb4-42c0-4536-b0ff-d2f733126ca3.png)
'

### Version

Community Edition v0.14.1

**Comment by jagodarybacka** [comment] 2022-08-09 12:47
I cannot reproduce this issue, checked on v0.14.2 ETH -> DAI, network fee works fine, swaped successfully. Closing for now.

**Comment by jagodarybacka** [comment] 2022-08-17 10:54
Reopening as another user had this problem

**Comment by Shadowfiend** [comment] 2022-08-17 11:51
What shows up in the fee details menu would be useful to know in this scenario.

**Comment by 0xDaedalus** [comment] 2023-02-14 21:16
No longer an issue

**Closed by 0xDaedalus** 2023-02-14 21:16 UTC
Labels: Type: Bug, Status: Pending, :video_game: Community Bug
